<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('vmt_country')->truncate();

        DB::table('vmt_country')->insert([
            ['id'=>'1','country_name' => 'Afghanistan', 'country_code' =>	'AF', 'dialing_code' => '+93', 'currency_name' => 'Afghan afghani ', 'currency_code' => 'AFN', 'timezone' => 'UTC+04:30 ', 'status' =>  'A'],
            ['id'=>'2','country_name' => 'Aland Islands', 'country_code' =>	'AX', 'dialing_code' => '+358', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'3','country_name' => 'Albania', 'country_code' =>	'AL', 'dialing_code' => '+355', 'currency_name' => 'Albanian lek ', 'currency_code' => 'ALL', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'4','country_name' => 'Algeria', 'country_code' =>	'DZ', 'dialing_code' => '+213', 'currency_name' => 'Algerian dinar ', 'currency_code' => 'DZD', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'5','country_name' => 'American Samoa', 'country_code' =>	'AS', 'dialing_code' => '+1', 'currency_name' => '', 'currency_code' => '', 'timezone' => 'UTC-11:00 ', 'status' =>  'A'],
            ['id'=>'6','country_name' => 'Andorra', 'country_code' =>	'AD', 'dialing_code' => '+376', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'7','country_name' => 'Angola', 'country_code' =>	'AO', 'dialing_code' => '+244', 'currency_name' => 'Angolan kwanza ', 'currency_code' => 'AOA', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'8','country_name' => 'Anguilla', 'country_code' =>	'AI', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'9','country_name' => 'Antarctica', 'country_code' =>	'AQ', 'dialing_code' => '+672', 'currency_name' => '', 'currency_code' => '', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'10','country_name' => 'Antigua and Barbuda', 'country_code' =>	'AG', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'11','country_name' => 'Argentina', 'country_code' =>	'AR', 'dialing_code' => '+54', 'currency_name' => 'Argentine peso ', 'currency_code' => 'ARS', 'timezone' => 'UTC-03:00 ', 'status' =>  'A'],
            ['id'=>'12','country_name' => 'Armenia', 'country_code' =>	'AM', 'dialing_code' => '+374', 'currency_name' => 'Armenian dram ', 'currency_code' => 'AMD', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'13','country_name' => 'Aruba', 'country_code' =>	'AW', 'dialing_code' => '+297', 'currency_name' => 'Aruban florin ', 'currency_code' => 'AWG', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'14','country_name' => 'Australia', 'country_code' =>	'AU', 'dialing_code' => '+61', 'currency_name' => 'Australian dollar ', 'currency_code' => 'AUD', 'timezone' => 'UTC+07:00 - UTC+10:00 ', 'status' =>  'A'],
            ['id'=>'15','country_name' => 'Austria', 'country_code' =>	'AT', 'dialing_code' => '+43', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'16','country_name' => 'Azerbaijan', 'country_code' =>	'AZ', 'dialing_code' => '+994', 'currency_name' => 'Azerbaijani manat ', 'currency_code' => 'AZN', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'17','country_name' => 'Bahamas', 'country_code' =>	'BS', 'dialing_code' => '+1', 'currency_name' => 'Bahamian dollar ', 'currency_code' => 'BSD', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'18','country_name' => 'Bahrain', 'country_code' =>	'BH', 'dialing_code' => '+973', 'currency_name' => 'Bahraini dinar ', 'currency_code' => 'BHD', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'19','country_name' => 'Bangladesh', 'country_code' =>	'BD', 'dialing_code' => '+880', 'currency_name' => 'Bangladeshi taka ', 'currency_code' => 'BDT', 'timezone' => 'UTC+06:00 ', 'status' =>  'A'],
            ['id'=>'20','country_name' => 'Barbados', 'country_code' =>	'BB', 'dialing_code' => '+1', 'currency_name' => 'Barbadian dollar ', 'currency_code' => 'BBD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'21','country_name' => 'Belarus', 'country_code' =>	'BY', 'dialing_code' => '+375', 'currency_name' => 'Belarusian ruble ', 'currency_code' => 'BYR', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'22','country_name' => 'Belgium', 'country_code' =>	'BE', 'dialing_code' => '+32', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'23','country_name' => 'Belize', 'country_code' =>	'BZ', 'dialing_code' => '+501', 'currency_name' => 'Belize dollar ', 'currency_code' => 'BZD', 'timezone' => 'UTC-06:00 ', 'status' =>  'A'],
            ['id'=>'24','country_name' => 'Benin', 'country_code' =>	'BJ', 'dialing_code' => '+229', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'25','country_name' => 'Bermuda', 'country_code' =>	'BM', 'dialing_code' => '+1', 'currency_name' => 'Bermudian dollar ', 'currency_code' => 'BMD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'26','country_name' => 'Bhutan', 'country_code' =>	'BT', 'dialing_code' => '+975', 'currency_name' => 'Bhutanese ngultrum ', 'currency_code' => 'BTN', 'timezone' => 'UTC+05:30 ', 'status' =>  'A'],
            ['id'=>'27','country_name' => 'Bolivia', 'country_code' =>	'BO', 'dialing_code' => '+591', 'currency_name' => 'Bolivian boliviano ', 'currency_code' => 'BOB', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'28','country_name' => 'Caribbean Netherlands', 'country_code' =>	'BQ', 'dialing_code' => '+599', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'29','country_name' => 'Bosnia and Herzegovina', 'country_code' =>	'BA', 'dialing_code' => '+387', 'currency_name' => 'Bosnia and Herzegovina convertible mark ', 'currency_code' => 'BAM', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'30','country_name' => 'Botswana', 'country_code' =>	'BW', 'dialing_code' => '+267', 'currency_name' => 'Botswana pula ', 'currency_code' => 'BWP', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'31','country_name' => 'Bouvet Island', 'country_code' =>	'BV', 'dialing_code' => '+55', 'currency_name' => '', 'currency_code' => '', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'32','country_name' => 'Brazil', 'country_code' =>	'BR', 'dialing_code' => '+55', 'currency_name' => 'Brazilian real ', 'currency_code' => 'BRL', 'timezone' => 'UTC-05:00', 'status' =>  'A'],
            ['id'=>'33','country_name' => 'British Indian Ocean Territory', 'country_code' =>	'IO', 'dialing_code' => '+246', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC+06 ', 'status' =>  'A'],
            ['id'=>'34','country_name' => 'Brunei', 'country_code' =>	'BN', 'dialing_code' => '+673', 'currency_name' => 'Brunei dollar ', 'currency_code' => 'BND', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'35','country_name' => 'Bulgaria', 'country_code' =>	'BG', 'dialing_code' => '+359', 'currency_name' => 'Bulgarian lev ', 'currency_code' => 'BGN', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'36','country_name' => 'Burkina Faso', 'country_code' =>	'BF', 'dialing_code' => '+226', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'37','country_name' => 'Burundi', 'country_code' =>	'BI', 'dialing_code' => '+257', 'currency_name' => 'Burundian franc ', 'currency_code' => 'BIF', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'38','country_name' => 'Cambodia', 'country_code' =>	'KH', 'dialing_code' => '+855', 'currency_name' => 'Cambodian riel ', 'currency_code' => 'KHR', 'timezone' => 'UTC+07:00 ', 'status' =>  'A'],
            ['id'=>'39','country_name' => 'Cameroon', 'country_code' =>	'CM', 'dialing_code' => '+237', 'currency_name' => 'Central African CFA franc ', 'currency_code' => 'XAF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'40','country_name' => 'Canada', 'country_code' =>	'CA', 'dialing_code' => '+1', 'currency_name' => 'Canadian dollar ', 'currency_code' => 'CAD', 'timezone' => 'UTC-08:00', 'status' =>  'A'],
            ['id'=>'41','country_name' => 'CapeVerde', 'country_code' =>	'CV', 'dialing_code' => '+238', 'currency_name' => 'Cape Verdean escudo ', 'currency_code' => 'CVE', 'timezone' => 'UTC-01:00 ', 'status' =>  'A'],
            ['id'=>'42','country_name' => 'Cayman Islands', 'country_code' =>	'KY', 'dialing_code' => '+1', 'currency_name' => 'Cayman Islands dollar ', 'currency_code' => 'KYD', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'43','country_name' => 'Central African Republic', 'country_code' =>	'CF', 'dialing_code' => '+236', 'currency_name' => 'Central African CFA franc ', 'currency_code' => 'XAF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'44','country_name' => 'Chad', 'country_code' =>	'TD', 'dialing_code' => '+235', 'currency_name' => 'Central African CFA franc ', 'currency_code' => 'XAF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'45','country_name' => 'Chile', 'country_code' =>	'CL', 'dialing_code' => '+56', 'currency_name' => 'Chilean peso ', 'currency_code' => 'CLP', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'46','country_name' => 'China', 'country_code' =>	'CN', 'dialing_code' => '+86', 'currency_name' => 'Chinese yuan ', 'currency_code' => 'CNY', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'47','country_name' => 'ChristmasIsland', 'country_code' =>	'CX', 'dialing_code' => '+61', 'currency_name' => 'Australian dollar ', 'currency_code' => 'AUD', 'timezone' => 'UTC+07 ', 'status' =>  'A'],
            ['id'=>'48','country_name' => 'Cocos(Keeling)Islands', 'country_code' =>	'CC', 'dialing_code' => '+891', 'currency_name' => 'Australian dollar ', 'currency_code' => 'AUD', 'timezone' => 'UTC+06:30 ', 'status' =>  'A'],
            ['id'=>'49','country_name' => 'Colombia', 'country_code' =>	'CO', 'dialing_code' => '+57', 'currency_name' => 'Colombian peso ', 'currency_code' => 'COP', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'50','country_name' => 'Comoros', 'country_code' =>	'KM', 'dialing_code' => '+269', 'currency_name' => 'Comorian franc ', 'currency_code' => 'KMF', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'51','country_name' => 'Republic of the Congo', 'country_code' =>	'CG', 'dialing_code' => '+242', 'currency_name' => 'Central African CFA franc ', 'currency_code' => 'XAF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'52','country_name' => 'Democratic Republic of the Congo', 'country_code' =>	'CD', 'dialing_code' => '+243', 'currency_name' => 'Congolese franc ', 'currency_code' => 'CDF', 'timezone' => 'UTC+01:00', 'status' =>  'A'],
            ['id'=>'53','country_name' => 'Cook Islands', 'country_code' =>	'CK', 'dialing_code' => '+682', 'currency_name' => 'New Zealand dollar ', 'currency_code' => 'NZD', 'timezone' => 'UTC-10:00 ', 'status' =>  'A'],
            ['id'=>'54','country_name' => 'CostaRica', 'country_code' =>	'CR', 'dialing_code' => '+506', 'currency_name' => 'Costa Rican colon ', 'currency_code' => 'CRC', 'timezone' => 'UTC-06:00 ', 'status' =>  'A'],
            ['id'=>'55','country_name' => 'Ivory Coast', 'country_code' =>	'CI', 'dialing_code' => '+225', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'56','country_name' => 'Croatia', 'country_code' =>	'HR', 'dialing_code' => '+385', 'currency_name' => 'Croatian kuna ', 'currency_code' => 'HRK', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'57','country_name' => 'Cuba', 'country_code' =>	'CU', 'dialing_code' => '+53', 'currency_name' => 'Cuban convertible peso ', 'currency_code' => 'CUC', 'timezone' => 'UTC-03:00 ', 'status' =>  'A'],
            ['id'=>'58','country_name' => 'Curacao', 'country_code' =>	'CW', 'dialing_code' => '+599', 'currency_name' => 'Netherlands Antillean guilder ', 'currency_code' => 'ANG', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'59','country_name' => 'Cyprus', 'country_code' =>	'CY', 'dialing_code' => '+357', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'60','country_name' => 'Czech Republic', 'country_code' =>	'CZ', 'dialing_code' => '+420', 'currency_name' => 'Czech koruna ', 'currency_code' => 'CZK', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'61','country_name' => 'Denmark', 'country_code' =>	'DK', 'dialing_code' => '+45', 'currency_name' => 'Danish krone ', 'currency_code' => 'DKK', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'62','country_name' => 'Djibouti', 'country_code' =>	'DJ', 'dialing_code' => '+253', 'currency_name' => 'Djiboutian franc ', 'currency_code' => 'DJF', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'63','country_name' => 'Dominica', 'country_code' =>	'DM', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'64','country_name' => 'Dominican Republic', 'country_code' =>	'DO', 'dialing_code' => '+1', 'currency_name' => 'Dominican peso ', 'currency_code' => 'DOP', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'65','country_name' => 'East Timor', 'country_code' =>	'TL', 'dialing_code' => '+670', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC+09 ', 'status' =>  'A'],
            ['id'=>'66','country_name' => 'Ecuador', 'country_code' =>	'EC', 'dialing_code' => '+593', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'67','country_name' => 'Egypt', 'country_code' =>	'EG', 'dialing_code' => '+20', 'currency_name' => 'Egyptian pound ', 'currency_code' => 'EGP', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'68','country_name' => 'El Salvador', 'country_code' =>	'SV', 'dialing_code' => '+503', 'currency_name' => 'Salvadoran colon ', 'currency_code' => 'SVC', 'timezone' => 'UTC-06:00 ', 'status' =>  'A'],
            ['id'=>'69','country_name' => 'Equatorial Guinea', 'country_code' =>	'GQ', 'dialing_code' => '+240', 'currency_name' => 'Central African CFA franc ', 'currency_code' => 'XAF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'70','country_name' => 'Eritrea', 'country_code' =>	'ER', 'dialing_code' => '+291', 'currency_name' => 'Eritrean nakfa ', 'currency_code' => 'ERN', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'71','country_name' => 'Estonia', 'country_code' =>	'EE', 'dialing_code' => '+372', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'72','country_name' => 'Ethiopia', 'country_code' =>	'ET', 'dialing_code' => '+251', 'currency_name' => 'Ethiopian birr ', 'currency_code' => 'ETB', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'73','country_name' => 'Falkland Islands (Islas Malvinas)', 'country_code' =>	'FK', 'dialing_code' => '+500', 'currency_name' => 'Falkland Islands pound ', 'currency_code' => 'FKP', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'74','country_name' => 'Faroe Islands', 'country_code' =>	'FO', 'dialing_code' => '+298', 'currency_name' => 'Danish krone ', 'currency_code' => 'DKK', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'75','country_name' => 'Fiji', 'country_code' =>	'FJ', 'dialing_code' => '+679', 'currency_name' => 'Fijian dollar ', 'currency_code' => 'FJD', 'timezone' => 'UTC+12:00 ', 'status' =>  'A'],
            ['id'=>'76','country_name' => 'Finland', 'country_code' =>	'FI', 'dialing_code' => '+358', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'77','country_name' => 'France', 'country_code' =>	'FR', 'dialing_code' => '+33', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'78','country_name' => 'French Guiana', 'country_code' =>	'GF', 'dialing_code' => '+594', 'currency_name' => '', 'currency_code' => '', 'timezone' => 'UTC-01:00 ', 'status' =>  'A'],
            ['id'=>'79','country_name' => 'French Polynesia', 'country_code' =>	'PF', 'dialing_code' => '+689', 'currency_name' => 'CFP franc ', 'currency_code' => 'XPF', 'timezone' => 'UTC-10:00 ', 'status' =>  'A'],
            ['id'=>'80','country_name' => 'French Southern and Antarctic Lands', 'country_code' =>	'TF', 'dialing_code' => '+262', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'81','country_name' => 'Gabon', 'country_code' =>	'GA', 'dialing_code' => '+241', 'currency_name' => 'Central African CFA franc ', 'currency_code' => 'XAF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'82','country_name' => 'Gambia', 'country_code' =>	'GM', 'dialing_code' => '+220', 'currency_name' => 'Gambian dalasi ', 'currency_code' => 'GMD', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'83','country_name' => 'Georgia', 'country_code' =>	'GE', 'dialing_code' => '+995', 'currency_name' => 'Georgian lari ', 'currency_code' => 'GEL', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'84','country_name' => 'Germany', 'country_code' =>	'DE', 'dialing_code' => '+49', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'85','country_name' => 'Ghana', 'country_code' =>	'GH', 'dialing_code' => '+233', 'currency_name' => 'Ghanaian cedi ', 'currency_code' => 'GHS', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'86','country_name' => 'Gibraltar', 'country_code' =>	'GI', 'dialing_code' => '+350', 'currency_name' => 'Gibraltar pound ', 'currency_code' => 'GIP', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'87','country_name' => 'Greece', 'country_code' =>	'GR', 'dialing_code' => '+30', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'88','country_name' => 'Greenland', 'country_code' =>	'GL', 'dialing_code' => '+299', 'currency_name' => 'Danish krone ', 'currency_code' => 'DKK', 'timezone' => 'UTC-03:00 ', 'status' =>  'A'],
            ['id'=>'89','country_name' => 'Grenada', 'country_code' =>	'GD', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'90','country_name' => 'Guadeloupe', 'country_code' =>	'GP', 'dialing_code' => '+590', 'currency_name' => '', 'currency_code' => '', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'91','country_name' => 'Guam', 'country_code' =>	'GU', 'dialing_code' => '+1', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC+10:00 ', 'status' =>  'A'],
            ['id'=>'92','country_name' => 'Guatemala', 'country_code' =>	'GT', 'dialing_code' => '+502', 'currency_name' => 'Guatemalan quetzal ', 'currency_code' => 'GTQ', 'timezone' => 'UTC-06:00 ', 'status' =>  'A'],
            ['id'=>'93','country_name' => 'Guernsey', 'country_code' =>	'GG', 'dialing_code' => '+44', 'currency_name' => 'Guernsey pound', 'currency_code' => '?GGP', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'94','country_name' => 'Guinea', 'country_code' =>	'GN', 'dialing_code' => '+224', 'currency_name' => 'Guinean franc ', 'currency_code' => 'GNF', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'95','country_name' => 'Guinea-Bissau', 'country_code' =>	'GW', 'dialing_code' => '+245', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'96','country_name' => 'Guyana', 'country_code' =>	'GY', 'dialing_code' => '+592', 'currency_name' => 'Guyanese dollar ', 'currency_code' => 'GYD', 'timezone' => 'UTC-03:00 ', 'status' =>  'A'],
            ['id'=>'97','country_name' => 'Haiti', 'country_code' =>	'HT', 'dialing_code' => '+509', 'currency_name' => 'Haitian gourde ', 'currency_code' => 'HTG', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'98','country_name' => 'Heard Island and McDonald Islands', 'country_code' =>	'HM', 'dialing_code' => '+0', 'currency_name' => '', 'currency_code' => '', 'timezone' => 'UTC+05 ', 'status' =>  'A'],
            ['id'=>'99','country_name' => 'Honduras', 'country_code' =>	'HN', 'dialing_code' => '+504', 'currency_name' => 'Honduran lempira ', 'currency_code' => 'HNL', 'timezone' => 'UTC-06:00 ', 'status' =>  'A'],
            ['id'=>'100','country_name' => 'HongKong', 'country_code' =>	'HK', 'dialing_code' => '+852', 'currency_name' => 'Hong Kong dollar ', 'currency_code' => 'HKD', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'101','country_name' => 'Hungary', 'country_code' =>	'HU', 'dialing_code' => '+36', 'currency_name' => 'Hungarian forint ', 'currency_code' => 'HUF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'102','country_name' => 'Iceland', 'country_code' =>	'IS', 'dialing_code' => '+354', 'currency_name' => 'Icelandic krona ', 'currency_code' => 'ISK', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'103','country_name' => 'India', 'country_code' =>	'IN', 'dialing_code' => '+91', 'currency_name' => 'Indian rupee ', 'currency_code' => 'INR', 'timezone' => 'UTC+05:30 ', 'status' =>  'A'],
            ['id'=>'104','country_name' => 'Indonesia', 'country_code' =>	'ID', 'dialing_code' => '+62', 'currency_name' => 'Indonesian rupiah ', 'currency_code' => 'IDR', 'timezone' => 'UTC+07:00', 'status' =>  'A'],
            ['id'=>'105','country_name' => 'Iran', 'country_code' =>	'IR', 'dialing_code' => '+98', 'currency_name' => 'Iranian rial ', 'currency_code' => 'IRR', 'timezone' => 'UTC+03:30 ', 'status' =>  'A'],
            ['id'=>'106','country_name' => 'Iraq', 'country_code' =>	'IQ', 'dialing_code' => '+964', 'currency_name' => 'Iraqi dinar ', 'currency_code' => 'IQD', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'107','country_name' => 'Ireland', 'country_code' =>	'IE', 'dialing_code' => '+353', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'108','country_name' => 'Isle of Man', 'country_code' =>	'IM', 'dialing_code' => '+44', 'currency_name' => 'Manx pound', 'currency_code' => 'IMP', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'109','country_name' => 'Israel', 'country_code' =>	'IL', 'dialing_code' => '+972', 'currency_name' => 'Israeli new shekel ', 'currency_code' => 'ILS', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'110','country_name' => 'Italy', 'country_code' =>	'IT', 'dialing_code' => '+39', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'111','country_name' => 'Jamaica', 'country_code' =>	'JM', 'dialing_code' => '+1', 'currency_name' => 'Jamaican dollar', 'currency_code' => 'JMD', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'112','country_name' => 'Japan', 'country_code' =>	'JP', 'dialing_code' => '+81', 'currency_name' => 'Japanese yen ', 'currency_code' => 'JPY', 'timezone' => 'UTC+09:00 ', 'status' =>  'A'],
            ['id'=>'113','country_name' => 'Jersey', 'country_code' =>	'JE', 'dialing_code' => '+44', 'currency_name' => 'Jersey  pound ', 'currency_code' => '?JEP', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'114','country_name' => 'Jordan', 'country_code' =>	'JO', 'dialing_code' => '+962', 'currency_name' => 'Jordanian dinar ', 'currency_code' => 'JOD', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'115','country_name' => 'Kazakhstan', 'country_code' =>	'KZ', 'dialing_code' => '+7', 'currency_name' => 'Kazakhstani tenge ', 'currency_code' => 'KZT', 'timezone' => 'UTC+06:00 ', 'status' =>  'A'],
            ['id'=>'116','country_name' => 'Kenya', 'country_code' =>	'KE', 'dialing_code' => '+254', 'currency_name' => 'Kenyan shilling ', 'currency_code' => 'KES', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'117','country_name' => 'Kiribati', 'country_code' =>	'KI', 'dialing_code' => '+686', 'currency_name' => 'Australian dollar ', 'currency_code' => 'AUD', 'timezone' => 'UTC+12:00 ', 'status' =>  'A'],
            ['id'=>'118','country_name' => 'Kuwait', 'country_code' =>	'KW', 'dialing_code' => '+965', 'currency_name' => 'Kuwaiti dinar ', 'currency_code' => 'KWD', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'119','country_name' => 'Kyrgyzstan', 'country_code' =>	'KG', 'dialing_code' => '+996', 'currency_name' => 'Kyrgyzstani som ', 'currency_code' => 'KGS', 'timezone' => 'UTC+06:00 ', 'status' =>  'A'],
            ['id'=>'120','country_name' => 'Laos', 'country_code' =>	'LA', 'dialing_code' => '+856', 'currency_name' => 'Lao kip ', 'currency_code' => 'LAK', 'timezone' => 'UTC+07:00 ', 'status' =>  'A'],
            ['id'=>'121','country_name' => 'Latvia', 'country_code' =>	'LV', 'dialing_code' => '+371', 'currency_name' => 'Latvian lats ', 'currency_code' => 'LVL', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'122','country_name' => 'Lebanon', 'country_code' =>	'LB', 'dialing_code' => '+961', 'currency_name' => 'Lebanese pound ', 'currency_code' => 'LBP', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'123','country_name' => 'Lesotho', 'country_code' =>	'LS', 'dialing_code' => '+266', 'currency_name' => 'Lesotho loti ', 'currency_code' => 'LSL', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'124','country_name' => 'Liberia', 'country_code' =>	'LR', 'dialing_code' => '+231', 'currency_name' => 'Liberian dollar ', 'currency_code' => 'LRD', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'125','country_name' => 'Libya', 'country_code' =>	'LY', 'dialing_code' => '+218', 'currency_name' => 'Libyan dinar ', 'currency_code' => 'LYD', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'126','country_name' => 'Liechtenstein', 'country_code' =>	'LI', 'dialing_code' => '+423', 'currency_name' => 'Swiss franc ', 'currency_code' => 'CHF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'127','country_name' => 'Lithuania', 'country_code' =>	'LT', 'dialing_code' => '+370', 'currency_name' => 'Lithuanian litas ', 'currency_code' => 'LTL', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'128','country_name' => 'Luxembourg', 'country_code' =>	'LU', 'dialing_code' => '+352', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'129','country_name' => 'Macau', 'country_code' =>	'MO', 'dialing_code' => '+853', 'currency_name' => 'Macanese pataca ', 'currency_code' => 'MOP', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'130','country_name' => 'Macedonia', 'country_code' =>	'MK', 'dialing_code' => '+389', 'currency_name' => 'Macedonian denar ', 'currency_code' => 'MKD', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'131','country_name' => 'Madagascar', 'country_code' =>	'MG', 'dialing_code' => '+261', 'currency_name' => 'Malagasy ariary ', 'currency_code' => 'MGA', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'132','country_name' => 'Malawi', 'country_code' =>	'MW', 'dialing_code' => '+265', 'currency_name' => 'Malawian kwacha ', 'currency_code' => 'MWK', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'133','country_name' => 'Malaysia', 'country_code' =>	'MY', 'dialing_code' => '+60', 'currency_name' => 'Malaysian ringgit ', 'currency_code' => 'MYR', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'134','country_name' => 'Maldives', 'country_code' =>	'MV', 'dialing_code' => '+960', 'currency_name' => 'Maldivian rufiyaa ', 'currency_code' => 'MVR', 'timezone' => 'UTC+05:00 ', 'status' =>  'A'],
            ['id'=>'135','country_name' => 'Mali', 'country_code' =>	'ML', 'dialing_code' => '+223', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'136','country_name' => 'Malta', 'country_code' =>	'MT', 'dialing_code' => '+356', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'137','country_name' => 'Marshall Islands', 'country_code' =>	'MH', 'dialing_code' => '+692', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC+10:00 ', 'status' =>  'A'],
            ['id'=>'138','country_name' => 'Martinique', 'country_code' =>	'MQ', 'dialing_code' => '+596', 'currency_name' => '', 'currency_code' => '', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'139','country_name' => 'Mauritania', 'country_code' =>	'MR', 'dialing_code' => '+222', 'currency_name' => 'Mauritanian ouguiya ', 'currency_code' => 'MRO', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'140','country_name' => 'Mauritius', 'country_code' =>	'MU', 'dialing_code' => '+230', 'currency_name' => 'Mauritian rupee ', 'currency_code' => 'MUR', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'141','country_name' => 'Mayotte', 'country_code' =>	'YT', 'dialing_code' => '+262', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'142','country_name' => 'Mexico', 'country_code' =>	'MX', 'dialing_code' => '+52', 'currency_name' => 'Mexican peso ', 'currency_code' => 'MXN', 'timezone' => 'UTC-06:00 ', 'status' =>  'A'],
            ['id'=>'143','country_name' => 'Federated States of Micronesia', 'country_code' =>	'FM', 'dialing_code' => '+691', 'currency_name' => 'Micronesian dollar ', 'currency_code' => 'None', 'timezone' => 'UTC+10:00 ', 'status' =>  'A'],
            ['id'=>'144','country_name' => 'Republic of Moldova', 'country_code' =>	'MD', 'dialing_code' => '+373', 'currency_name' => 'Moldovan leu ', 'currency_code' => 'MDL', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'145','country_name' => 'Monaco', 'country_code' =>	'MC', 'dialing_code' => '+377', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'146','country_name' => 'Mongolia', 'country_code' =>	'MN', 'dialing_code' => '+976', 'currency_name' => 'Mongolian togrog ', 'currency_code' => 'MNT', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'147','country_name' => 'Montenegro', 'country_code' =>	'ME', 'dialing_code' => '+382', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01 ', 'status' =>  'A'],
            ['id'=>'148','country_name' => 'Montserrat', 'country_code' =>	'MS', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'149','country_name' => 'Morocco', 'country_code' =>	'MA', 'dialing_code' => '+212', 'currency_name' => 'Moroccan dirham ', 'currency_code' => 'MAD', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'150','country_name' => 'Mozambique', 'country_code' =>	'MZ', 'dialing_code' => '+258', 'currency_name' => 'Mozambican metical ', 'currency_code' => 'MZN', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'151','country_name' => 'Myanmar', 'country_code' =>	'MM', 'dialing_code' => '+95', 'currency_name' => 'Myanma kyat ', 'currency_code' => 'MMK', 'timezone' => 'UTC+06:30 ', 'status' =>  'A'],
            ['id'=>'152','country_name' => 'Namibia', 'country_code' =>	'NA', 'dialing_code' => '+264', 'currency_name' => 'Namibian dollar ', 'currency_code' => 'NAD', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'153','country_name' => 'Nauru', 'country_code' =>	'NR', 'dialing_code' => '+674', 'currency_name' => 'Australian dollar ', 'currency_code' => 'AUD', 'timezone' => 'UTC+12:00 ', 'status' =>  'A'],
            ['id'=>'154','country_name' => 'Nepal', 'country_code' =>	'NP', 'dialing_code' => '+977', 'currency_name' => 'Nepalese rupee ', 'currency_code' => 'NPR', 'timezone' => 'UTC+05:30 ', 'status' =>  'A'],
            ['id'=>'155','country_name' => 'Netherlands', 'country_code' =>	'NL', 'dialing_code' => '+31', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'156','country_name' => 'New Caledonia', 'country_code' =>	'NC', 'dialing_code' => '+687', 'currency_name' => 'CFP franc ', 'currency_code' => 'XPF', 'timezone' => 'UTC+11:00 ', 'status' =>  'A'],
            ['id'=>'157','country_name' => 'New Zealand', 'country_code' =>	'NZ', 'dialing_code' => '+64', 'currency_name' => 'New Zealand dollar ', 'currency_code' => 'NZD', 'timezone' => 'UTC+12:00 ', 'status' =>  'A'],
            ['id'=>'158','country_name' => 'Nicaragua', 'country_code' =>	'NI', 'dialing_code' => '+505', 'currency_name' => 'Nicaraguan crodoba ', 'currency_code' => 'NIO', 'timezone' => 'UTC-06:00 ', 'status' =>  'A'],
            ['id'=>'159','country_name' => 'Niger', 'country_code' =>	'NE', 'dialing_code' => '+227', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'160','country_name' => 'Nigeria', 'country_code' =>	'NG', 'dialing_code' => '+234', 'currency_name' => 'Nigerian naira ', 'currency_code' => 'NGN', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'161','country_name' => 'Niue', 'country_code' =>	'NU', 'dialing_code' => '+683', 'currency_name' => 'New Zealand dollar ', 'currency_code' => 'NZD', 'timezone' => 'UTC-11:00 ', 'status' =>  'A'],
            ['id'=>'162','country_name' => 'Norfolk Island', 'country_code' =>	'NF', 'dialing_code' => '+672', 'currency_name' => 'Australian dollar ', 'currency_code' => 'AUD', 'timezone' => 'UTC+11:30 ', 'status' =>  'A'],
            ['id'=>'163','country_name' => 'North Korea', 'country_code' =>	'KP', 'dialing_code' => '+850', 'currency_name' => 'North Korean won ', 'currency_code' => 'KPW', 'timezone' => 'UTC+09:00 ', 'status' =>  'A'],
            ['id'=>'164','country_name' => 'Northern Mariana Islands', 'country_code' =>	'MP', 'dialing_code' => '+1', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC+10:00 ', 'status' =>  'A'],
            ['id'=>'165','country_name' => 'Norway', 'country_code' =>	'NO', 'dialing_code' => '+47', 'currency_name' => 'Norwegian krone ', 'currency_code' => 'NOK', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'166','country_name' => 'Oman', 'country_code' =>	'OM', 'dialing_code' => '+968', 'currency_name' => 'Omani rial ', 'currency_code' => 'OMR', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'167','country_name' => 'Pakistan', 'country_code' =>	'PK', 'dialing_code' => '+92', 'currency_name' => 'Pakistani rupee ', 'currency_code' => 'PKR', 'timezone' => 'UTC+05:00 ', 'status' =>  'A'],
            ['id'=>'168','country_name' => 'Palau', 'country_code' =>	'PW', 'dialing_code' => '+680', 'currency_name' => 'Palauan dollar ', 'currency_code' => 'None', 'timezone' => 'UTC+09:00 ', 'status' =>  'A'],
            ['id'=>'169','country_name' => 'PalestinianTerritory,Occupied', 'country_code' =>	'PS', 'dialing_code' => '+970', 'currency_name' => '', 'currency_code' => '', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'170','country_name' => 'Panama', 'country_code' =>	'PA', 'dialing_code' => '+507', 'currency_name' => 'Panamanian balboa ', 'currency_code' => 'PAB', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'171','country_name' => 'Papua New Guinea', 'country_code' =>	'PG', 'dialing_code' => '+675', 'currency_name' => 'Papua New Guinean kina ', 'currency_code' => 'PGK', 'timezone' => 'UTC+10:00 ', 'status' =>  'A'],
            ['id'=>'172','country_name' => 'Paraguay', 'country_code' =>	'PY', 'dialing_code' => '+595', 'currency_name' => 'Paraguayan guarani', 'currency_code' => 'PYG', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'173','country_name' => 'Peru', 'country_code' =>	'PE', 'dialing_code' => '+51', 'currency_name' => 'Peruvian nuevo sol ', 'currency_code' => 'PEN', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'174','country_name' => 'Philippines', 'country_code' =>	'PH', 'dialing_code' => '+63', 'currency_name' => 'Philippine peso ', 'currency_code' => 'PHP', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'175','country_name' => 'Pitcairn', 'country_code' =>	'PN', 'dialing_code' => '+872', 'currency_name' => 'New Zealand dollar ', 'currency_code' => 'NZD', 'timezone' => 'UTC-08 ', 'status' =>  'A'],
            ['id'=>'176','country_name' => 'Poland', 'country_code' =>	'PL', 'dialing_code' => '+48', 'currency_name' => 'Polish zloty ', 'currency_code' => 'PLN', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'177','country_name' => 'Portugal', 'country_code' =>	'PT', 'dialing_code' => '+351', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'178','country_name' => 'Puerto Rico', 'country_code' =>	'PR', 'dialing_code' => '+1', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'179','country_name' => 'Qatar', 'country_code' =>	'QA', 'dialing_code' => '+974', 'currency_name' => 'Qatari riyal ', 'currency_code' => 'QAR', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'180','country_name' => 'Reunion', 'country_code' =>	'RE', 'dialing_code' => '+262', 'currency_name' => '', 'currency_code' => '', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'181','country_name' => 'Romania', 'country_code' =>	'RO', 'dialing_code' => '+40', 'currency_name' => 'Romanian leu ', 'currency_code' => 'RON', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'182','country_name' => 'Russia', 'country_code' =>	'RU', 'dialing_code' => '+7', 'currency_name' => 'Russian ruble ', 'currency_code' => 'RUB', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'183','country_name' => 'Rwanda', 'country_code' =>	'RW', 'dialing_code' => '+250', 'currency_name' => 'Rwandan franc ', 'currency_code' => 'RWF', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'184','country_name' => 'Saint Barthelemy', 'country_code' =>	'BL', 'dialing_code' => '+590', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC-04 ', 'status' =>  'A'],
            ['id'=>'185','country_name' => 'Saint Helena', 'country_code' =>	'SH', 'dialing_code' => '+290', 'currency_name' => 'Saint Helena pound ', 'currency_code' => 'SHP', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'186','country_name' => 'Saint Kitts and Nevis', 'country_code' =>	'KN', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'187','country_name' => 'Saint Lucia', 'country_code' =>	'LC', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'188','country_name' => 'Saint Martin(Frenchpart)', 'country_code' =>	'MF', 'dialing_code' => '+590', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC-04 ', 'status' =>  'A'],
            ['id'=>'189','country_name' => 'Saint Pierreand Miquelon', 'country_code' =>	'PM', 'dialing_code' => '+508', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC-03 ', 'status' =>  'A'],
            ['id'=>'190','country_name' => 'Saint Vincent and the Grenadines', 'country_code' =>	'VC', 'dialing_code' => '+1', 'currency_name' => 'East Caribbean dollar ', 'currency_code' => 'XCD', 'timezone' => 'UTC-04 ', 'status' =>  'A'],
            ['id'=>'191','country_name' => 'Samoa', 'country_code' =>	'WS', 'dialing_code' => '+685', 'currency_name' => 'Samoan tala ', 'currency_code' => 'WST', 'timezone' => 'UTC-11:00 ', 'status' =>  'A'],
            ['id'=>'192','country_name' => 'San Marino', 'country_code' =>	'SM', 'dialing_code' => '+378', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'193','country_name' => 'Sao Tome and Principe', 'country_code' =>	'ST', 'dialing_code' => '+239', 'currency_name' => 'Sao Tome and Principe dobra ', 'currency_code' => 'STD', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'194','country_name' => 'Saudi Arabia', 'country_code' =>	'SA', 'dialing_code' => '+966', 'currency_name' => 'Saudi riyal ', 'currency_code' => 'SAR', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'195','country_name' => 'Senegal', 'country_code' =>	'SN', 'dialing_code' => '+221', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'196','country_name' => 'Serbia', 'country_code' =>	'RS', 'dialing_code' => '+381', 'currency_name' => 'Serbian dinar ', 'currency_code' => 'RSD', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'197','country_name' => 'Seychelles', 'country_code' =>	'SC', 'dialing_code' => '+248', 'currency_name' => 'Seychellois rupee ', 'currency_code' => 'SCR', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'198','country_name' => 'Sierra Leone', 'country_code' =>	'SL', 'dialing_code' => '+232', 'currency_name' => 'Sierra Leonean leone ', 'currency_code' => 'SLL', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'199','country_name' => 'Singapore', 'country_code' =>	'SG', 'dialing_code' => '+65', 'currency_name' => 'Brunei dollar ', 'currency_code' => 'BND', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'200','country_name' => 'Sint Maarten', 'country_code' =>	'SX', 'dialing_code' => '+1', 'currency_name' => 'Netherlands Antillean guilder ', 'currency_code' => 'ANG', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'201','country_name' => 'Slovakia', 'country_code' =>	'SK', 'dialing_code' => '+421', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'202','country_name' => 'Slovenia', 'country_code' =>	'SI', 'dialing_code' => '+386', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'203','country_name' => 'Solomon Islands', 'country_code' =>	'SB', 'dialing_code' => '+677', 'currency_name' => 'Solomon Islands dollar ', 'currency_code' => 'SBD', 'timezone' => 'UTC+11:00 ', 'status' =>  'A'],
            ['id'=>'204','country_name' => 'Somalia', 'country_code' =>	'SO', 'dialing_code' => '+252', 'currency_name' => 'Somali shilling ', 'currency_code' => 'SOS', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'205','country_name' => 'South Africa', 'country_code' =>	'ZA', 'dialing_code' => '+27', 'currency_name' => 'South African rand ', 'currency_code' => 'ZAR', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'206','country_name' => 'South Georgia and the South Sandwich Islands', 'country_code' =>	'GS', 'dialing_code' => '+500', 'currency_name' => 'British pound ', 'currency_code' => 'GBP', 'timezone' => 'UTC-02 ', 'status' =>  'A'],
            ['id'=>'207','country_name' => 'South Korea', 'country_code' =>	'KR', 'dialing_code' => '+82', 'currency_name' => 'South Korean won ', 'currency_code' => 'KRW', 'timezone' => 'UTC+09:00 ', 'status' =>  'A'],
            ['id'=>'208','country_name' => 'Spain', 'country_code' =>	'ES', 'dialing_code' => '+34', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'209','country_name' => 'SriLanka', 'country_code' =>	'LK', 'dialing_code' => '+94', 'currency_name' => 'Sri Lankan rupee ', 'currency_code' => 'LKR', 'timezone' => 'UTC+05:30 ', 'status' =>  'A'],
            ['id'=>'210','country_name' => 'Sudan', 'country_code' =>	'SD', 'dialing_code' => '+249', 'currency_name' => 'Sudanese pound ', 'currency_code' => 'SDG', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'211','country_name' => 'Suriname', 'country_code' =>	'SR', 'dialing_code' => '+597', 'currency_name' => 'Surinamese dollar ', 'currency_code' => 'SRD', 'timezone' => 'UTC-03:30 ', 'status' =>  'A'],
            ['id'=>'212','country_name' => 'Svalbard and Jan Mayen', 'country_code' =>	'SJ', 'dialing_code' => '+47', 'currency_name' => '', 'currency_code' => '', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'213','country_name' => 'Swaziland', 'country_code' =>	'SZ', 'dialing_code' => '+268', 'currency_name' => 'Swazi lilangeni ', 'currency_code' => 'SZL', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'214','country_name' => 'Sweden', 'country_code' =>	'SE', 'dialing_code' => '+46', 'currency_name' => 'Swedish krona ', 'currency_code' => 'SEK', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'215','country_name' => 'Switzerland', 'country_code' =>	'CH', 'dialing_code' => '+41', 'currency_name' => 'Swiss franc ', 'currency_code' => 'CHF', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'216','country_name' => 'Syrian Arab Republic', 'country_code' =>	'SY', 'dialing_code' => '+963', 'currency_name' => 'Syrian pound ', 'currency_code' => 'SYP', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'217','country_name' => 'Taiwan', 'country_code' =>	'TW', 'dialing_code' => '+886', 'currency_name' => 'New Taiwan dollar ', 'currency_code' => 'TWD', 'timezone' => 'UTC+08:00 ', 'status' =>  'A'],
            ['id'=>'218','country_name' => 'Tajikistan', 'country_code' =>	'TJ', 'dialing_code' => '+992', 'currency_name' => 'Tajikistani somoni ', 'currency_code' => 'TJS', 'timezone' => 'UTC+06:00 ', 'status' =>  'A'],
            ['id'=>'219','country_name' => 'Tanzania', 'country_code' =>	'TZ', 'dialing_code' => '+255', 'currency_name' => 'Tanzanian shilling ', 'currency_code' => 'TZS', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'220','country_name' => 'Thailand', 'country_code' =>	'TH', 'dialing_code' => '+66', 'currency_name' => 'Thai baht ', 'currency_code' => 'THB', 'timezone' => 'UTC+07:00 ', 'status' =>  'A'],
            ['id'=>'221','country_name' => 'Togo', 'country_code' =>	'TG', 'dialing_code' => '+228', 'currency_name' => 'West African CFA franc ', 'currency_code' => 'XOF', 'timezone' => 'UTC ', 'status' =>  'A'],
            ['id'=>'222','country_name' => 'Tokelau', 'country_code' =>	'TK', 'dialing_code' => '+690', 'currency_name' => 'New Zealand dollar ', 'currency_code' => 'NZD', 'timezone' => 'UTC-10 ', 'status' =>  'A'],
            ['id'=>'223','country_name' => 'Tonga', 'country_code' =>	'TO', 'dialing_code' => '+676', 'currency_name' => 'Tongan paoanga ', 'currency_code' => 'TOP', 'timezone' => 'UTC+13:00 ', 'status' =>  'A'],
            ['id'=>'224','country_name' => 'Trinidad and Tobago', 'country_code' =>	'TT', 'dialing_code' => '+1', 'currency_name' => 'Trinidad and Tobago dollar ', 'currency_code' => 'TTD', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'225','country_name' => 'Tunisia', 'country_code' =>	'TN', 'dialing_code' => '+216', 'currency_name' => 'Tunisian dinar ', 'currency_code' => 'TND', 'timezone' => 'UTC+01:00 ', 'status' =>  'A'],
            ['id'=>'226','country_name' => 'Turkey', 'country_code' =>	'TR', 'dialing_code' => '+90', 'currency_name' => 'Turkish lira ', 'currency_code' => 'TRY', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'227','country_name' => 'Turkmenistan', 'country_code' =>	'TM', 'dialing_code' => '+993', 'currency_name' => 'Turkmenistani manat ', 'currency_code' => 'TMT', 'timezone' => 'UTC+05:00 ', 'status' =>  'A'],
            ['id'=>'228','country_name' => 'Turksand Caicos Islands', 'country_code' =>	'TC', 'dialing_code' => '+1', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC-05:00 ', 'status' =>  'A'],
            ['id'=>'229','country_name' => 'Tuvalu', 'country_code' =>	'TV', 'dialing_code' => '+688', 'currency_name' => 'Australian dollar ', 'currency_code' => 'AUD', 'timezone' => 'UTC+12:00 ', 'status' =>  'A'],
            ['id'=>'230','country_name' => 'Uganda', 'country_code' =>	'UG', 'dialing_code' => '+256', 'currency_name' => 'Ugandan shilling ', 'currency_code' => 'UGX', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'231','country_name' => 'Ukraine', 'country_code' =>	'UA', 'dialing_code' => '+380', 'currency_name' => 'Ukrainian hryvnia ', 'currency_code' => 'UAH', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'232','country_name' => 'United Arab Emirates', 'country_code' =>	'AE', 'dialing_code' => '+971', 'currency_name' => 'United Arab Emirates dirham ', 'currency_code' => 'AED', 'timezone' => 'UTC+04:00 ', 'status' =>  'A'],
            ['id'=>'233','country_name' => 'United Kingdom', 'country_code' =>	'GB', 'dialing_code' => '+44', 'currency_name' => 'Pound sterling', 'currency_code' => 'GBP', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'234','country_name' => 'United States', 'country_code' =>	'US', 'dialing_code' => '+1', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC-11:00', 'status' =>  'A'],
            ['id'=>'235','country_name' => 'United States Minor Outlying Islands', 'country_code' =>	'UM', 'dialing_code' => '+1', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'236','country_name' => 'Uruguay', 'country_code' =>	'UY', 'dialing_code' => '+598', 'currency_name' => 'Uruguayan peso ', 'currency_code' => 'UYU', 'timezone' => 'UTC-03:00 ', 'status' =>  'A'],
            ['id'=>'237','country_name' => 'Uzbekistan', 'country_code' =>	'UZ', 'dialing_code' => '+998', 'currency_name' => 'Uzbekistani som ', 'currency_code' => 'UZS', 'timezone' => 'UTC+06:00 ', 'status' =>  'A'],
            ['id'=>'238','country_name' => 'Vanuatu', 'country_code' =>	'VU', 'dialing_code' => '+678', 'currency_name' => 'Vanuatu vatu ', 'currency_code' => 'VUV', 'timezone' => 'UTC+11:00 ', 'status' =>  'A'],
            ['id'=>'239','country_name' => 'VaticanCity', 'country_code' =>	'VA', 'dialing_code' => '+379', 'currency_name' => 'Euro ', 'currency_code' => 'EUR', 'timezone' => 'UTC+01 ', 'status' =>  'A'],
            ['id'=>'240','country_name' => 'Venezuela', 'country_code' =>	'VE', 'dialing_code' => '+58', 'currency_name' => 'Venezuelan bolivar', 'currency_code' => 'VEF', 'timezone' => 'UTC-04:00 ', 'status' =>  'A'],
            ['id'=>'241','country_name' => 'Vietnam', 'country_code' =>	'VN', 'dialing_code' => '+84', 'currency_name' => 'Vietnamese dong', 'currency_code' => 'VND', 'timezone' => 'UTC+07:00 ', 'status' =>  'A'],
            ['id'=>'242','country_name' => 'British Virgin Islands', 'country_code' =>	'VG', 'dialing_code' => '+1', 'currency_name' => 'British Virgin Islands dollar ', 'currency_code' => 'None', 'timezone' => 'UTC-04 ', 'status' =>  'A'],
            ['id'=>'243','country_name' => 'United States Virgin Islands', 'country_code' =>	'VI', 'dialing_code' => '+1', 'currency_name' => 'United States dollar ', 'currency_code' => 'USD', 'timezone' => 'UTC-04 ', 'status' =>  'A'],
            ['id'=>'244','country_name' => 'WallisandFutuna', 'country_code' =>	'WF', 'dialing_code' => '+681', 'currency_name' => 'CFP franc ', 'currency_code' => 'XPF', 'timezone' => 'UTC+12:00 ', 'status' =>  'A'],
            ['id'=>'245','country_name' => 'WesternSahara', 'country_code' =>	'EH', 'dialing_code' => '+212', 'currency_name' => 'Moroccan dirham ', 'currency_code' => 'MAD', 'timezone' => '', 'status' =>  'A'],
            ['id'=>'246','country_name' => 'Yemen', 'country_code' =>	'YE', 'dialing_code' => '+967', 'currency_name' => 'Yemeni rial ', 'currency_code' => 'YER', 'timezone' => 'UTC+03:00 ', 'status' =>  'A'],
            ['id'=>'247','country_name' => 'Zambia', 'country_code' =>	'ZM', 'dialing_code' => '+260', 'currency_name' => 'Zambian kwacha ', 'currency_code' => 'ZMK', 'timezone' => 'UTC+02:00 ', 'status' =>  'A'],
            ['id'=>'248','country_name' => 'Zimbabwe', 'country_code' =>	'ZW', 'dialing_code' => '+263', 'currency_name' => 'Botswana pula ', 'currency_code' => 'BWP', 'timezone' => 'UTC+02:00 ', 'status' =>  'A']
        ]);
    }
}
